name: Run Python Script and Notify Slack

on:
  schedule:
   - cron: '20 14 * * *' 
  workflow_dispatch:
  
jobs: 
  run-script: 
    runs-on: ubuntu-latest 
    steps:
          
      - name: Checkout Repository 
        uses: actions/checkout@v2
        
      - name: Set up Python 
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.x'  
          
      - name: Install Dependencies 
        run: | 
          python -m pip install --upgrade pip  
      
      - name: Run Python Script  
        id: run_script 
        run: | 
          python validation.py | tee script_output.log

      - name: check for success
        id: c_s
        run: |
          if grep "Successfull post validation" script_output.log; then
            echo "status=success" >> $GITHUB_ENV 
          else
            echo "status=failure" >> $GITHUB_ENV
          fi
        

      - name: Send GitHub Action trigger data to Slack workflow in success
        if: env.status == 'success'
        uses: slackapi/slack-github-action@v1.26.0 
        with:
          status: ${{ job.status }}
          channel: 'githubAction'
          payload: |
            {
              "text": "O/P of python script: success"
            }
        env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK    

      - name: Send GitHub Action trigger data to Slack workflow in failure
        if: env.status == 'failure'
        uses: .github/slack-notify@main   #voxmedia/github-action-slack-notify-build@v1 
        with:
          status: ${{ job.status }}
          payload: |
            {
              "channel": 'githubAction',
              "attachments": [
                {
                  "color": "${{ env.status == 'success' && '#36a64f' || '#FF0000' }}",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "Job *${{ env.status }}* for *${{ github.workflow }}*:\n*<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>*"
                      }
                    }
                  ]
                }
              ]
            }
        env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          
