name: Run Python Script and Notify Slack

on:
  schedule:
   - cron: '20 14 * * *' 
  workflow_dispatch:
  
jobs: 
  run-script: 
    runs-on: ubuntu-latest 
    steps:
          
      - name: Checkout Repository 
        uses: actions/checkout@v2
        
      - name: Set up Python 
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.x'  
          
      - name: Install Dependencies 
        run: | 
          python -m pip install --upgrade pip  
      
      - name: Run Python Script  
        id: run-script 
        run: | 
          python validation.py | tee script_output.log

      - name: Send GitHub Action trigger data to Slack workflow
        if: always()
        uses: ./.github/actions/lib/slack-notify # slackapi/slack-github-action@v1.26.0   voxmedia/github-action-slack-notify-build@v1 
        with:
          status: ${{ job.status }}
          channel: 'githubAction'
          fields: job,commit,repo,author 
          payload: |
            {
              "text": "O/P of python script:",
              "attachment": [
                {
                "text": "$(cat script_output.log)"
                }
              ]
            }
        env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          
